#!/bin/sh
# Seed every fixture through the local upload API and report job ids.
#
# This walks the two-step TRD §8.1 contract for each fixture:
#   1. POST /api/v1/ingest/uploads           -> { jobId, uploadUrl, ... }
#   2. PUT  /api/v1/ingest/uploads/:job/content   (the actual bytes)
#
# Processing is async, so this script only confirms each job was accepted
# (HTTP 202) and prints the jobId. Poll with:
#   make job-status JOB_ID=<jobId>
#
# Usage:
#   make seed                       # uses http://127.0.0.1:8080
#   API_BASE=http://host:port make seed
#
# Requires: the API is running (make run-local) and fixtures exist
# (make fixtures for the shapefile bundles).

set -eu

API_BASE="${API_BASE:-http://127.0.0.1:8080}"
TENANT="${TENANT:-tenant-acme}"

ROOT="$(cd "$(dirname "$0")/.." && pwd)"
FIXTURES="$ROOT/tests/fixtures"

if ! command -v python3 >/dev/null 2>&1; then
    echo "error: python3 is required (used to parse JSON responses)" >&2
    exit 1
fi
if ! command -v curl >/dev/null 2>&1; then
    echo "error: curl is required" >&2
    exit 1
fi

# Confirm the API is up before doing anything.
if ! curl -fsS "$API_BASE/healthz" >/dev/null 2>&1; then
    echo "error: API not reachable at $API_BASE (start it with: make run-local)" >&2
    exit 1
fi

json_field() {
    # json_field '<json>' <field>  -> prints the string value of a top-level key
    printf '%s' "$1" | python3 -c "import sys,json; print(json.load(sys.stdin).get('$2',''))"
}

# seed <file> <layerId> <format> <category> <contentType> [tags...]
seed() {
    file="$1"; layer="$2"; format="$3"; category="$4"; ctype="$5"
    name="$(basename "$file")"

    if [ ! -f "$file" ]; then
        printf 'skip  %-28s (missing: %s)\n' "$layer" "$name"
        return 0
    fi

    tags=""
    if [ "$#" -gt 5 ]; then
        shift 5
        for t in "$@"; do
            if [ -z "$tags" ]; then tags="\"$t\""; else tags="$tags,\"$t\""; fi
        done
    fi

    body="$(printf '{"tenantId":"%s","layerId":"%s","fileName":"%s","contentType":"%s","sourceFormat":"%s","metadata":{"name":"%s","category":"%s","tags":[%s]}}' \
        "$TENANT" "$layer" "$name" "$ctype" "$format" "$layer" "$category" "$tags")"

    resp="$(curl -fsS -X POST "$API_BASE/api/v1/ingest/uploads" \
        -H 'Content-Type: application/json' -d "$body")" || {
        printf 'FAIL  %-28s (upload request rejected)\n' "$layer"; return 0; }

    job="$(json_field "$resp" jobId)"
    if [ -z "$job" ]; then
        printf 'FAIL  %-28s (no jobId: %s)\n' "$layer" "$resp"
        return 0
    fi

    code="$(curl -s -o /dev/null -w '%{http_code}' -X PUT \
        "$API_BASE/api/v1/ingest/uploads/$job/content" \
        -H "Content-Type: $ctype" --data-binary "@$file")"
    if [ "$code" = "202" ]; then
        printf 'ok    %-28s jobId=%s\n' "$layer" "$job"
    else
        printf 'FAIL  %-28s jobId=%s content-upload HTTP %s\n' "$layer" "$job" "$code"
    fi
}

echo "Seeding fixtures into $API_BASE (tenant=$TENANT)"
echo

# GeoJSON fixtures (checked in).
seed "$FIXTURES/simple-parcels.geojson"       us-parcels-nyc       GEOJSON PARCEL      application/geo+json parcel valuation nyc
seed "$FIXTURES/assets-points.geojson"        us-assets-points     GEOJSON ASSET_POINT application/geo+json asset points
seed "$FIXTURES/null-island.geojson"          null-island          GEOJSON ASSET_POINT application/geo+json edge-case
seed "$FIXTURES/oversized-properties.geojson" oversized-properties GEOJSON PARCEL      application/geo+json edge-case
seed "$FIXTURES/invalid-polygon.geojson"      invalid-polygon      GEOJSON PARCEL      application/geo+json edge-case invalid

# Shapefile fixtures (generated by `make fixtures`).
seed "$FIXTURES/small-parcels.zip"            small-parcels-shp    SHAPEFILE PARCEL    application/zip parcel shapefile
seed "$FIXTURES/missing-dbf.zip"              missing-dbf          SHAPEFILE PARCEL    application/zip edge-case invalid
seed "$FIXTURES/missing-prj.zip"              missing-prj          SHAPEFILE PARCEL    application/zip edge-case unknown-crs

echo
echo "Poll a job with: make job-status JOB_ID=<jobId>"
